version: '3.3'
services:
  db:
    image: mysql/mysql-server:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3322'
    volumes:
      - my-db:/var/lib/mysql

  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    ports:
        - '8081:8080'
        - '50000:50000'
    volumes:
        - jenkins_home:/var/jenkins_home

volumes:

   my-db:
   jenkins_home:

