apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_PASSWORD: cGFzc3dvcmQ=  # password encodé en base64
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # root password encodé en base64
