---
- name: Deploy to Kubernetes
  hosts: all
  # become: true
  become_user: zaidbr
  vars:
    kubernetes_deployments_dir: "../../kubernetes/deployments"
  tasks:
    - name: Initialiser le cluster Minikube
      shell: "export PATH=$PATH:/usr/local/bin && minikube start --driver=docker"

    - name: Deploy MySQL to Kubernetes
      ansible.builtin.command:
        cmd: "export PATH=$PATH:/usr/local/bin && kubectl apply -f {{ kubernetes_deployments_dir }}/mysql-deployment.yaml"
      register: mysql_output

    - name: Show MySQL Deployment Status
      ansible.builtin.debug:
        msg: "{{ mysql_output.stdout }}"

    - name: Deploy Backend to Kubernetes
      ansible.builtin.command:
        cmd: "export PATH=$PATH:/usr/local/bin && kubectl apply -f {{ kubernetes_deployments_dir }}/backend-deployment.yaml"
      register: backend_output

    - name: Show Backend Deployment Status
      ansible.builtin.debug:
        msg: "{{ backend_output.stdout }}"
