---
- hosts: all
  become: true
  tasks:
    # - name: Mise à jour des paquets
    #   apt:
    #     update_cache: yes
    
    # - name: Installer les dépendances
    #   apt:
    #     name:
    #       - apt-transport-https
    #       - ca-certificates
    #       - curl
    #       - software-properties-common
    #     state: present

    # - name: Ajouter la clé GPG de Docker
    #   apt_key:
    #     url: https://download.docker.com/linux/ubuntu/gpg
    #     state: present

    # - name: Ajouter le dépôt Docker
    #   apt_repository:
    #     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    #     state: present
    
    # - name: Installer Docker
    #   apt:
    #     name: docker-ce
    #     state: present
    
    # - name: Activer et démarrer Docker
    #   systemd:
    #     name: docker
    #     enabled: true
    #     state: started
    
    # - name: Ajouter la clé GPG de Kubernetes
      # shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -


    # - name: Ajouter le dépôt Kubernetes
    #   apt_repository:
    #     repo: "deb https://apt.kubernetes.io/ kubernetes-focal main"
    #     state: present
    #     filename: "kubernetes.list"
        
    # - name: Mettre à jour la liste des paquets
    #   apt:
    #     update_cache: yes
    
    # - name: Installer kubelet, kubeadm, and kubectl
    #   apt:
    #     name:
    #       - kubelet
    #       - kubeadm
    #       - kubectl
    #     state: present
    #     force_apt_get: true
    
    # - name: Démarrer kubectl
    #   systemd:
    #     name: kubectl
    #     enabled: true
    #     state: started
    
    # - name: Désactiver le swap (nécessaire pour Kubernetes)
    #   command: swapoff -a
    
 
    - name: Initialiser le cluster Minikube
      ansible.builtin.shell: |
        export PATH=$PATH:/usr/local/bin
        minikube start --driver=none
